stages:
  - build
  - archive

variables:
  LC_ALL: "en_US.UTF-8"

before_script:
  - pod install

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace OctagonAnalytics.xcworkspace -scheme OctagonAnalytics | xcpretty
  tags:
    - OctagonAnalytics

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -workspace OctagonAnalytics.xcworkspace -archivePath OctagonAnalytics.xcarchive -scheme OctagonAnalytics
    - xcodebuild -exportArchive -archivePath OctagonAnalytics.xcarchive -exportOptionsPlist OctagonAnalytics/exportOptions.plist -exportPath $PWD/build
  only:
    - master
    - tags
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/
  tags:
    - OctagonAnalytics
